### ISSUE TITLE
Sites incompatible

### ISSUE THREAD

**Issue by JustrynaLearn** [dzt/trimalchio#1]
Hi,
It works marvellously, thank you for your hard work.
However just wanted to raise something with you.
For certain sites it says sites incompatible rather than take me to checkout. 
any idea why?
see below and thank you again!

> [Sun May 21 2017 12:49:53] [WARN]  Found an existing config.json, using data from file for current process.
> [Sun May 21 2017 12:49:53] [LOG]   Looking for Keyword(s) matching "Corporate Orange Dino Polo"
> Press Enter to continue...
> [Sun May 21 2017 12:49:54] [LOG]   Item Found! - "Corporate Orange Dino Polo"
> [Sun May 21 2017 12:49:54] [LOG]   Style/Size Choice #1: "SMALL" | Stock: undefined)
> [Sun May 21 2017 12:49:54] [LOG]   Style/Size Choice #2: "MEDIUM" | Stock: undefined)
> [Sun May 21 2017 12:49:54] [LOG]   Style/Size Choice #3: "LARGE" | Stock: undefined)
> [Sun May 21 2017 12:49:54] [LOG]   Style/Size Choice #4: "EXTRA LARGE" | Stock: undefined)
> [Sun May 21 2017 12:49:54] [LOG]   Style/Size Choice #5: "EXTRA EXTRA LARGE" | Stock: undefined)
> Input: Select a Style # (ex: "1"):  2
> [Sun May 21 2017 12:49:55] [LOG]   You selected - "MEDIUM" (28071043017)
> [Sun May 21 2017 12:49:56] [LOG]   Added to cart!
> [Sun May 21 2017 12:49:56] [LOG]   Checking out your item...
> [Sun May 21 2017 12:49:57] [LOG]   Store ID: 4146229
> [Sun May 21 2017 12:49:57] [LOG]   Checkout ID: 4193739472dc20d01c785d7575782e62
> [Sun May 21 2017 12:49:57] [LOG]   Checkout URL: https://checkout.shopify.com/4146229/checkouts/4193739472dc20d01c785d7575782e62
> [Sun May 21 2017 12:49:57] [LOG]   Checkout with checkout.shopify.com discovered
> [Sun May 21 2017 12:49:59] [LOG]   https://store.illegalcivilization.com/ is Incompatible, sorry for the inconvenience

**Comment by dzt** [comment]
Some of the methods I'm using aren't 100% on all the sites as of right now. Do you mean having it directly open up the checkout page (in the browser) if it's incompatible?
