### ISSUE TITLE
Issue with checkout

### ISSUE THREAD

**Issue by ghost** [dzt/trimalchio#6]
Any Shopify site I try it doesn't checkout it says this is not compatible, running OS X.

**Comment by seankuendig** [comment]
Hi, I saw that you opened 3 issues but all of them are very vague with little to no information. Would be great if you could provide more info and steps on how to reproduce these errors.

**Comment by dfa82** [comment]
I'm having a similar problem, this might help. I created a new issue (https://github.com/dzt/trimalchio/issues/9)
